#!/bin/bash

if grep -q "return luci.sys.call(\"/etc/init.d/turboacc check_status fastpath >/dev/null\") == 0" "/usr/lib/lua/luci/controller/turboacc.lua" ; then
    exit 0
else
    sed -i 's/return luci\.sys\.call("\/etc\/init\.d\/turboacc check_status fastpath") == 0/return luci.sys.call("\/etc\/init.d\/turboacc check_status fastpath \>\/dev\/null") == 0/' "/usr/lib/lua/luci/controller/turboacc.lua"
    rm -rf /tmp/luci-indexcache
    rm -rf /tmp/luci-modulecache/
fi
