#!/bin/sh

if [ "$ACTION" = "ifup" ] && [ "$INTERFACE" = "wan" ]; then
    [ -x /etc/init.d/miniupnpd ] || exit 0
    /etc/init.d/miniupnpd enabled >/dev/null 2>&1 || exit 0
    [ "$(uci -q get upnpd.config.enabled)" = "1" ] || exit 0
    sleep 60
    /usr/bin/update-upnp.sh
fi
